<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNvu5g2f\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNvu5g2f/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNvu5g2f.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNvu5g2f\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNvu5g2f\App_KernelDevDebugContainer([
    'container.build_hash' => 'Nvu5g2f',
    'container.build_id' => 'a4f9338a',
    'container.build_time' => 1657110385,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNvu5g2f');
